repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.22.0
  hooks:
  - id: pyupgrade
    args: [--py3-plus, --keep-runtime-typing]

- repo: https://github.com/python/black
  rev: 21.7b0
  hooks:
  - id: black
    language_version: python3

- repo: https://github.com/timothycrosley/isort
  rev: 5.9.2
  hooks:
    - id: isort
      additional_dependencies: [toml]
      args: ["--profile", "black", "--filter-files"]
      exclude: ^.*/?setup\.py$

- repo: https://gitlab.com/pycqa/flake8
  rev: 3.9.2
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-bugbear==21.4.3
      - flake8-builtins==1.5.3
      - flake8-comprehensions==3.5.0
      - flake8-eradicate==1.1.0
      - flake8-pytest-style==1.5.0
      - flake8-mutable==1.2.0
      - flake8-pytest-style==1.5.0
      - pep8-naming==0.12.0


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.910
  hooks:
  - id: mypy
    additional_dependencies:
      - types-PyYAML >= 5.4.10


- repo: https://github.com/asottile/blacken-docs
  rev: v1.10.0
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==21.7b0]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
      exclude: ^tests/.*/fixtures/.*
    - id: end-of-file-fixer
      exclude: ^tests/.*/fixtures/.*
    - id: debug-statements
